### ISSUE TITLE
MSVC does not support and, or, etc in lieu of &&, ||, etc...

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11-connector-mysql#13]
Hi,

Just downloaded the current version of sqlpp11-connector-mysql and tried to compile the tests with Visual Studio 2015 Update 2 and it fails because it does not yet support:

and, or, ..... instead of &&, || ...

The solution seems very simple: just #define these words. The only question: where is the best place? Do we create a separate .h and include it in all .h?

Regards,
Juan

**Comment by rbock** [comment]
Can you check if ciso646 is included? It contains those aliases for compilers like MSVC.

It is included in sqlpp11/logic.h, for instance.

Thanks for looking into this. I plan to add appveyor CI, but of course it helps a lot if most problems are gone by then, because debugging via CI is horribly time consuming.

Best,

Roland

**Comment by juandent** [comment]
Hi!

It is not included... should we include it in every .h?

Regards,
Juan

**Comment by juandent** [comment]
-- sorry should not have closed it yet

**Comment by rbock** [comment]
Hi Juan,

I would not like to include it in every .h. The problem occurs in 

src/bind_result.cpp
src/char_result.cpp
src/prepared_statement.cpp

I assume?

We could either add the include in those files or replace the 'and'/'or' with `&&` and `||`. I am fine with both. Maybe you can create a pull request?

Best,

Roland

**Comment by juandent** [comment]
Will be my pleasure Roland

**Comment by juandent** [comment]
Hi Roland

Had a problem with my computer
Please give me a while

Regards
Juan
