### ISSUE TITLE
{char,bind}_result_t.size() is unimplemented

### ISSUE THREAD

**Issue by ku4sbi** [rbock/sqlpp11-connector-mysql#59]

**Comment by rbock** [comment]
That is correct. I did not add it myself, because it is not possible to provide a `size()` function for all connectors and in the beginning I wanted them to be as similar as possible.

However, there are differences between connectors, of course. I'd be open to a pull request to add `.size()` to results in the mysql connector.

**Comment by ZerQAQ** [comment]
where is that pull request? if the function is implied. does that mean we can get the result size from db(sqlpp::select(...)) without going through the iterator?

**Comment by rbock** [comment]
Yes, having `result.size()` could make sense if you wanted to call `vector::reserve`, for instance.

As mentioned initially, not all databases support that, which is why I did not implement it. If you really want it, I am open for a pull request, though.

**Comment by zhengminlai** [comment]
> Yes, having `result.size()` could make sense if you wanted to call `vector::reserve`, for instance.
> 
> As mentioned initially, not all databases support that, which is why I did not implement it. If you really want it, I am open for a pull request, though.

Hi, has the pull request been created? `result.size()` is actually very necessary when using mysql connector.

**Comment by rbock** [comment]
Not yet. Do you want to give it a try?
